spring:
  datasource:
    url: jdbc:mysql://47.93.32.243:3306/test
    username: waterproject2
    password: waterproject20200224
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
